config/routes.rb
Rails.application.routes.draw do
  constraints(host: /^eventask.herokuapp.com/) do
    get ':any', to: redirect('http://eventask.org')
  end

  root 'events#index'

  get 'events/archived' => 'events#archived'
  get 'events/refresh' => 'events#refresh'
  post 'events/:uid/update' => 'events#update', as: :event_update
  post 'events/:uid/archive' => 'events#archive', as: :event_archive
  post 'events/:uid/restore' => 'events#restore', as: :event_restore

  get 'settings' => 'calendars#index'
  post 'calendars' => 'calendars#update'

  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :calendar

  TASK_STATUSES = {
    done: 'done',
    not_done: nil
  }

  ATTRIBUTES_TO_SYNCHRONIZE = %w(summary start_datetime html_link color)

  validates :task_status, inclusion: { in: TASK_STATUSES.values }, allow_nil: true

  scope :not_done, -> { where(task_status: TASK_STATUSES.fetch(:not_done)) }
  scope :done, -> { where(task_status: TASK_STATUSES.fetch(:done)) }
  scope :visible, -> { where(archived: false).order(:start_datetime) }
  scope :archived, -> { where(archived: true).order(:start_datetime) }
  scope :future, -> { where('start_datetime > ?', DateTime.now) }
  scope :past, -> { where('start_datetime <= ? ', DateTime.now) }


  def done?
    task_status == TASK_STATUSES.fetch(:done)
  end

  def merge_google_event(google_event, calendar_uid)
    google_event = Event::GoogleEventAdapter.new(self, google_event)

    self.calendar_id = user.calendars.find_by_uid(calendar_uid).id

    ATTRIBUTES_TO_SYNCHRONIZE.each do |attribute|
      setter = "#{attribute}="
      value = google_event.send(attribute)
      self.send(setter, value)
    end
  end

  def merge_google_event!(google_event, calendar_uid)
    merge_google_event(google_event, calendar_uid)
    save!
  end

  def default_color
    calendar.background_color
  end
end

app/models/event/google_event_adapter.rb
class Event::GoogleEventAdapter

  def initialize(event, google_event)
    @event = event
    @google_event = google_event
  end

  def summary
    @google_event.fetch('summary')
  end

  def start_datetime
    start['date'] || start.fetch('dateTime')
  end

  def start
    @google_event.fetch('start')
  end

  def html_link
    @google_event.fetch('htmlLink')
  end

  def color
    custom_color || @event.default_color
  end

  private

  def color_id
    @google_event['colorId']
  end

  def custom_color
    events_colors[color_id].try(:fetch, 'background')
  end

  def events_colors
    @events_colors ||= @event.user.color.colors.fetch('event')
  end

end

app/models/event/synchronizer.rb
class Event::Synchronizer

  SYNCHRONIZE_FROM = 2.days
  SYNCHRONIZE_TO = 7.days

  def initialize(user)
    @user = user  
  end

  def synchronize!
    remove_deleted_events!
    merge_google_events!
  end

  private

  def merge_google_events!
    google_events_grouped_by_calendar_uid.each do |calendar_uid, google_events|
      google_events.each do |google_event|
        find_or_initialize_event(google_event.fetch('id')).tap do |event|
          event.merge_google_event!(google_event, calendar_uid)
        end
      end
    end
  end

  def remove_deleted_events!
    events.not_done.each do |event|
      event.destroy unless event.uid.in? google_events_uids
    end
  end

  def find_or_initialize_event(google_event_id)
    events.find_by_uid(google_event_id) || events.new(uid: google_event_id)
  end

  def events
    @events ||= @user.events
  end

  def google_events_uids
    @google_calendar_events_uids ||= google_events_grouped_by_calendar_uid.values.flatten.map do |google_calendar_event|
      google_calendar_event.fetch('id')
    end
  end

  def google_events_grouped_by_calendar_uid
    @google_calendar_events ||= google_calendar.events_grouped_by_calendars_uids(
      calendars_to_synchronize_uids,
      from: SYNCHRONIZE_FROM, to: SYNCHRONIZE_TO
    )
  end

  def calendars_to_synchronize_uids
    @user.calendars.to_synchronize.pluck(:uid)
  end

  def google_calendar
    @calendar ||= GoogleCalendar.new(@user)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :get_event, only: [:update, :archive, :restore]

  def index
    events = current_user.events.visible
    @events_to_do = events.not_done
    @events_done  = events.done
  end

  def archived
    @events = current_user.events.archived
  end

  def update
    checked = params.fetch(:checked) == 'true'
    @event.update_attribute(:task_status, checked ? Event::TASK_STATUSES.fetch(:done) : nil)
    head :ok
  end

  def archive
    @event.update_attribute(:archived, true)
    redirect_to root_path, notice: 'Event archived'
  end

  def restore
    @event.update_attributes(archived: false, task_status: params[:task_status])
    redirect_to root_path, notice: 'Event restored'
  end

  def refresh
    Event::Synchronizer.new(current_user).synchronize!
    redirect_to root_path, notice: 'Events synchronized with Google Calendar'
  rescue Google::APIClient::AuthorizationError
    redirect_to signout_path
  end

  private

  def get_event
    @event = Event.find_by_uid(params.fetch(:uid))
  end

end

app/views/events/_done.slim
section.events-list.done.small-12.columns
  h3 Done
  ul.list-unstyled
    - events.each do |event|
      li style="border-left: 25px solid #{event.color}; padding-left: 5px"
        span
          label
            input [
              type="checkbox"
              name= event.uid
              checked= event.done?
              id= event.uid
              title="Mark as undone"
              data-update-event-status= true
              data-event-uid= event.uid
              data-update-event-url= event_update_path(event.uid)
            ]
          = link_to event.summary, event.html_link, target: '_BLANK'
        span.right
          = link_to 'Archive', event_archive_path(event.uid), method: :post, class: 'button tiny'

app/views/events/_events.html.slim
section.events-list.small-12.columns
  h3= table_title
  ul.list-unstyled
    - events.each do |event|
      li style="border-left: 25px solid #{event.color}; padding-left: 5px"
        span
          label for=event.uid 
            input [
              type="checkbox"
              name= event.uid
              checked= event.done?
              id= event.uid
              title="Mark as done"
              data-update-event-status= true
              data-event-uid= event.uid
              data-update-event-url= event_update_path(event.uid)
            ]
          = link_to event.summary, event.html_link, target: '_BLANK'
        span.right
          - time_distance = Time.now - event.start_datetime
          - if time_distance > 0
            = distance_of_time_in_words(Time.now, event.start_datetime) + ' ago'
          - else
            = 'In ' + distance_of_time_in_words(Time.now, event.start_datetime)

app/views/events/_no_events.html.slim
p You have no events yet.
p
  = link_to 'Retrieve events', events_refresh_path
  |  from Google Calendar.

app/views/events/archived.slim
- if @events.empty?
  p You have no archived events.
  = link_to 'Back', root_path, class: 'button tiny'
- else
 section.events-list.archive.small-12.columns
  h3 Archived events
  ul.list-unstyled
    - @events.each do |event|
      li
        span.title
          = link_to event.summary, event.html_link, target: '_BLANK'
        span.right.restore
          = link_to 'Restore', event_restore_path(event.uid, task_status: Event::TASK_STATUSES.fetch(:done)), method: :post, class: 'button tiny'

app/views/events/index.html.slim
- if current_user.events.count < 1
  = render 'events/no_events'
- else
  = render 'events/events', events: @events_to_do, table_title: 'To do'
  = render 'events/done', events: @events_done