config/routes.rb
Rails.application.routes.draw do
  constraints(host: /^eventask.herokuapp.com/) do
    get ':any', to: redirect('http://eventask.org')
  end

  root 'events#index'

  get 'events/archived' => 'events#archived'
  get 'events/refresh' => 'events#refresh'
  post 'events/:uid/update' => 'events#update', as: :event_update
  post 'events/:uid/archive' => 'events#archive', as: :event_archive
  post 'events/:uid/restore' => 'events#restore', as: :event_restore

  get 'settings' => 'calendars#index'
  post 'calendars' => 'calendars#update'

  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base

  belongs_to :user

  scope :ordered, -> { order(:summary) }
  scope :to_synchronize, -> { where(synchronize: true) }

  def merge_google_calendar!(google_calendar)
    merge_google_calendar(google_calendar)
    save!
  end

  def merge_google_calendar(google_calendar)
    self.uid = google_calendar.fetch('id')
    self.summary = google_calendar.fetch('summary')
    self.background_color = google_calendar.fetch('backgroundColor')
  end

end

app/models/calendar/synchronizer.rb
class Calendar::Synchronizer

  def initialize(user)
    @user = user  
  end

  def synchronize!
    remove_deleted_calendars!
    merge_google_calendars!
  end
  
  private

  def merge_google_calendars!
    all_user_calendars.each do |google_calendar|
      find_or_initialize_calendar(google_calendar.fetch('id')).tap do |calendar|
        calendar.merge_google_calendar!(google_calendar)
      end
    end
  end

  def remove_deleted_calendars!
    @user.calendars.each do |calendar|
      calendar.destroy unless calendar.uid.in? google_calendars_uids
    end
  end

  def find_or_initialize_calendar(google_calendar_id)
    @user.calendars.find_by_uid(google_calendar_id) || @user.calendars.new(uid: google_calendar_id)
  end

  def all_user_calendars
    google_calendar.all_calendars
  end

  def google_calendars_uids
    @google_calendars_uids ||= all_user_calendars.map do |google_calendar|
      google_calendar.fetch('id')
    end
  end

  def google_calendar
    @calendar ||= GoogleCalendar.new(@user)
  end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

  before_action :get_calendar, only: [:update]

  def index
    @calendars = current_user.calendars.ordered
  end

  def update
    @calendar.update_attribute(:synchronize, params.fetch(:checked) == 'true')
    head :ok
  end

  private

  def get_calendar
    @calendar = current_user.calendars.find_by_uid(params.fetch(:calendar_id))
  end

end

app/views/calendars/index.html.slim
section.events-list.small-12.columns
  h3 Choose calendars to synchronize
  ul.list-unstyled
    - @calendars.each do |calendar|
      /TODO: refactor CSS
      li style="border-left: 25px solid #{calendar.background_color}; padding-left: 5px"
        span
          label for=calendar.uid
            input [
              type="checkbox"
              name= calendar.uid
              checked= calendar.synchronize
              id= calendar.uid
              data-update-calendars= true
              data-url= calendars_path
              data-calendar-id= calendar.uid
              ]
          = calendar.summary

  = link_to 'Back', root_path, class: 'button tiny right'