config/routes.rb
Rails.application.routes.draw do
  constraints(host: /^eventask.herokuapp.com/) do
    get ':any', to: redirect('http://eventask.org')
  end

  root 'events#index'

  get 'events/archived' => 'events#archived'
  get 'events/refresh' => 'events#refresh'
  post 'events/:uid/update' => 'events#update', as: :event_update
  post 'events/:uid/archive' => 'events#archive', as: :event_archive
  post 'events/:uid/restore' => 'events#restore', as: :event_restore

  get 'settings' => 'calendars#index'
  post 'calendars' => 'calendars#update'

  get '/auth/google_oauth2/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

end

app/views/layouts/_flash.html.slim
- flashes = { :notice => 'success', :alert => 'standard', :error => 'alert', :secondary => 'secondary' }
- flashes.each do |key, value|
  - if flash[key]
    .alert-box.medium-3.columns.visible-for-medium-up class= value data-alert=''
      = flash[key]
      = link_to '&times;'.html_safe, '#', :class => 'close'

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="author" content="Kacper Walanus, Pawel Kowalski"
    title EvenTask - Mark Google Calendar events as done

    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags

  body

    = render 'layouts/flash'

    nav.top-bar data-topbar="" role="navigation"
      ul.title-area
        li.name
          h1
            = link_to root_path do
              / TODO: refactor CSS
              span style="color: #01ACE4" E
              span style="color: #ccc" v
              span style="color: #ccc" e
              span style="color: #ccc" n
              span style="color: #01ACE4" T
              span style="color: #ccc" a
              span style="color: #ccc" s
              span style="color: #ccc" k
        li.toggle-topbar.menu-icon= link_to 'Menu', '#'

      section.top-bar-section
        ul.right
          li= link_to 'Synchronize events', events_refresh_path, class: 'button'
          li= link_to 'Settings', settings_path
          li= link_to 'Calendar', 'https://www.google.com/calendar', target: '_BLANK'
          li= link_to 'Contact', 'https://bitbucket.org/kv109/eventask/issues/new', target: '_BLANK'
          li= link_to 'Archive', events_archived_path
          li= link_to 'Sign out', signout_path
    .row
      .small-12.column
        = yield
        
    = javascript_include_tag "application"

    - if Rails.env.production? && !current_user.developer?
      javascript:
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-66831309-1', 'auto');
        ga('send', 'pageview');